### ISSUE TITLE
Status bar time has variable width

### ISSUE THREAD

**Issue by GermanKiwi** [Magisk-Modules-Repo/Magisk_Font_Google#2]
Hi, I've installed this Magisk module on my phone (Pixel XL marlin) - it looks fantastic!

However, I have the seconds enabled for the time in my status bar (via System UI Tuner > Status bar > Time). And I noticed that the overall width of the time increases and decreases depending on which digit is shown in the last position. This also results in the other icons on the status bar - like wifi, battery, etc - also being pushed to the left and right as well, as the width of the time changes each second.

It's most noticable when the last digit of the time changes from 0 to 1, as these two digits are the widest and thinnest respectively. However, the width changes to a lesser degree when the last digit changes from other numbers too.

This effect also exists even when seconds are turned off, and the time only shows hours and minutes - however, in this case it's less obvious because the last digit then only changes once every 60 seconds, rather than once each second.

Is this something that you're able to control in any way? To make the width of the time area fixed? Obviously the font itself is a variable-width font, but I'm hoping it's possible to make the time area fixed somehow.

The stock system font on my phone doesn't have this problem at all - when that font is in use, the width of the time is fixed.

**Comment by pirasalbe** [comment]
I'm sorry but the font was made by Google. I just created this Magisk Module, so I'm not able to fix this problem
